//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public int Id { get; set; }
        public int MyProperty { get; set; }
        public int Wins { get; set; }
        public string Motiv { get; set; }
        public string U1 { get; set; }
        public string U2 { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTime Created { get; set; }
        public string Type { get; set; }
        public string Pgn { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
