//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Body { get; set; }
        public string Send { get; set; }
        public string Type { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> Receiver_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
