//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puzzle
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string FeInit { get; set; }
        public string Fenfinish { get; set; }
        public string Nummoves { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int Corrects { get; set; }
        public int Intents { get; set; }
        public Nullable<int> CreatedBy_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
